import React from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import './styles.css';

type Screen = 'home' | 'create' | 'join' | 'random' | 'game';

const players = [
  { name: 'Nova', color: 'red', pos: 'top' },
  { name: 'You', color: 'green', pos: 'right' },
  { name: 'Milo', color: 'yellow', pos: 'bottom' },
  { name: 'Zara', color: 'blue', pos: 'left' },
];

function Logo() { return <div className="logo"><span className="logoMark">●</span><span>Ludo<span className="accent">.io</span></span></div> }

function Home({ go }: { go: (s: Screen) => void }) {
  return <main className="home"><div className="orb orbA"/><div className="orb orbB"/><header><Logo/><button className="avatar">S</button></header><section className="hero"><div className="eyebrow">REAL-TIME • 2–4 PLAYERS</div><h1>Roll. Race.<br/><span>Dominate.</span></h1><p>Classic Ludo, rebuilt for the .io generation. Play friends or jump into the global queue.</p><div className="actions"><button className="primary" onClick={() => go('create')}>Play Online <b>→</b></button><button className="secondary" onClick={() => go('random')}><span className="pulse"/> Play With Random Players</button></div><div className="quick"><button onClick={() => go('create')}>＋ Create Room</button><button onClick={() => go('join')}>↗ Join Room</button><button>?</button></div></section><div className="preview"><div className="miniBoard">{Array.from({length:49}).map((_,i)=><div key={i} className={`cell c${i}`}/>)}</div><div className="previewLabel"><span>LIVE MATCH</span><strong>12,482 players online</strong></div></div><footer><span>How to Play</span><span>Settings</span><span>v0.1 MVP</span></footer></main>
}

function Create({ go }: { go: (s: Screen) => void }) { return <main className="panelPage"><header><button className="back" onClick={()=>go('home')}>←</button><Logo/></header><section className="card"><div className="eyebrow">NEW MATCH</div><h2>Create a room</h2><p className="muted">Set the rules, invite friends, and start when everyone is ready.</p><label>YOUR NAME<input defaultValue="Sahal"/></label><label>PLAYERS<div className="seg"><button>2</button><button>3</button><button className="selected">4</button></div></label><label>ROOM TYPE<div className="seg wide"><button className="selected">Private</button><button>Public</button></div></label><label>ROOM PASSWORD <span className="optional">optional</span><input placeholder="Leave blank for none"/></label><button className="primary full" onClick={()=>go('game')}>Create Room <b>→</b></button></section></main> }
function Join({ go }: { go: (s: Screen) => void }) { return <main className="panelPage"><header><button className="back" onClick={()=>go('home')}>←</button><Logo/></header><section className="card"><div className="eyebrow">JOIN MATCH</div><h2>Enter room code</h2><p className="muted">Ask the host for their 8-character room code.</p><label>ROOM CODE<input className="code" placeholder="LUDO-4821" maxLength={9}/></label><label>YOUR NAME<input defaultValue="Sahal"/></label><button className="primary full" onClick={()=>go('game')}>Join Game <b>→</b></button></section></main> }
function Random({ go }: { go: (s: Screen) => void }) { return <main className="panelPage"><header><button className="back" onClick={()=>go('home')}>←</button><Logo/></header><section className="match"><div className="spinner"><div/></div><div className="eyebrow">MATCHMAKING</div><h2>Finding players<span className="dots">...</span></h2><p className="muted">Looking for the perfect match</p><div className="queue"><strong>2 / 4</strong><span>players found</span><div className="bar"><i/></div></div><button className="secondary" onClick={()=>go('home')}>Cancel</button></section></main> }

function Board({ go }: { go: (s: Screen) => void }) { return <main className="game"><header><Logo/><div className="room"><span>ROOM</span> LUDO-4821 <button>⧉</button></div><button className="icon">⚙</button></header><div className="gameLayout"><aside className="playerSide"><Player p={players[0]} active/><Player p={players[3]}/></aside><section className="boardWrap"><div className="turn">NOVA'S TURN <b>00:18</b></div><div className="board"><div className="homeZone redZone">{[1,2,3,4].map(i=><span key={i}/>)}</div><div className="homeZone greenZone">{[1,2,3,4].map(i=><span key={i}/>)}</div><div className="homeZone yellowZone">{[1,2,3,4].map(i=><span key={i}/>)}</div><div className="homeZone blueZone">{[1,2,3,4].map(i=><span key={i}/>)}</div><div className="track">{Array.from({length:52}).map((_,i)=><div key={i} className={`trackCell t${i}`}/>)}</div><div className="center"><span>◆</span></div><div className="piece redPiece">●</div><div className="piece greenPiece p2">●</div><div className="piece yellowPiece p3">●</div><div className="piece bluePiece p4">●</div></div><div className="diceRow"><button className="dice" onClick={()=>{}}>⚄</button><span>Tap dice to roll</span></div></section><aside className="playerSide right"><Player p={players[1]} active/><Player p={players[2]}/></aside></div><div className="gameBar"><button className="mic">● <span>Mic</span></button><div><b>Your turn</b><small>Roll the dice to continue</small></div><button className="leave" onClick={()=>go('home')}>Leave</button></div></main> }
function Player({p,active}:{p:typeof players[number],active?:boolean}) { return <div className={`player ${active?'active':''}`}><div className={`playerAvatar ${p.color}`}>{p.name[0]}</div><div><b>{p.name}</b><small>{active?'● Connected':'● Ready'}</small></div>{active&&<span className="micDot">●</span>}</div> }
function App(){const [screen,setScreen]=React.useState<Screen>('home'); return screen==='home'?<Home go={setScreen}/>:screen==='create'?<Create go={setScreen}/>:screen==='join'?<Join go={setScreen}/>:screen==='random'?<Random go={setScreen}/>:<Board go={setScreen}/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
