import express from 'express';import{createServer}from'node:http';import{Server}from'socket.io';import cors from'cors';import{createGame,roll,legalMoves,movePiece,resetForRematch,Color,Player,Game}from'./game.js';
+const app=express();app.use(cors());app.use(express.json());app.get('/health',(_,res)=>res.json({ok:true,service:'ludo.io'}));const http=createServer(app);const io=new Server(http,{cors:{origin:'*'}});type Room={code:string;host:string;maxPlayers:number;locked:boolean;password?:string;game:Game;members:Map<string,string>};const rooms=new Map<string,Room>();const queue=new Set<string>();const colors:Color[]=['red','green','yellow','blue'];
+const code=()=>{let c='';do c=`LUDO-${Math.floor(1000+Math.random()*9000)}`;while(rooms.has(c));return c};const snapshot=(r:Room)=>({code:r.code,host:r.host,maxPlayers:r.maxPlayers,locked:r.locked,state:r.game});const roomOf=(id:string)=>{for(const r of rooms.values())if(r.members.has(id))return r};const playerOf=(r:Room,id:string)=>r.game.players.findIndex(p=>p.id===id);const emit=(r:Room)=>io.to(r.code).emit('game:state',snapshot(r));
+function start(r:Room){r.game.phase='playing';r.game.turn=0;r.game.deadline=Date.now()+20000;r.game.players.forEach(p=>p.ready=true);emit(r)}
+function timer(r:Room){setTimeout(()=>{if(r.game.phase!=='playing'||!r.game.deadline||Date.now()<r.game.deadline)return;if(r.game.dice!==null){r.game.dice=null;r.game.turn=(r.game.turn+1)%r.game.players.length;r.game.lastAction='Turn timed out';r.game.deadline=Date.now()+20000;emit(r)}else{r.game.deadline=Date.now()+20000}},20500)}
+io.on('connection',s=>{
+ s.on('room:create',(d,ack)=>{const r:Room={code:code(),host:s.id,maxPlayers:Math.min(4,Math.max(2,Number(d?.maxPlayers)||4)),locked:false,password:d?.password||undefined,game:createGame(),members:new Map()};r.game.players.push({id:s.id,name:String(d?.name||'Player').slice(0,20),ready:false,connected:true,color:colors[0],pieces:[0,0,0,0].map(progress=>({progress})),muted:true,lastSeen:Date.now()});r.members.set(s.id,s.id);rooms.set(r.code,r);s.join(r.code);ack?.({ok:true,...snapshot(r)})});
+ s.on('room:join',(d,ack)=>{const r=rooms.get(String(d?.code||'').toUpperCase());if(!r)return ack?.({ok:false,error:'Room not found'});if(r.locked)return ack?.({ok:false,error:'Room is locked'});if(r.password&&r.password!==String(d?.password||''))return ack?.({ok:false,error:'Wrong password'});if(r.game.players.length>=r.maxPlayers)return ack?.({ok:false,error:'Room is full'});const p:Player={id:s.id,name:String(d?.name||'Player').slice(0,20),ready:false,connected:true,color:colors[r.game.players.length],pieces:[0,0,0,0].map(progress=>({progress})),muted:true,lastSeen:Date.now()};r.game.players.push(p);r.members.set(s.id,s.id);s.join(r.code);emit(r);ack?.({ok:true,...snapshot(r)})});
+ s.on('room:ready',()=>{const r=roomOf(s.id);if(!r||r.game.phase!=='lobby')return;const p=r.game.players.find(x=>x.id===s.id);if(p)p.ready=!p.ready;emit(r)});
+ s.on('room:lock',()=>{const r=roomOf(s.id);if(r?.host===s.id){r.locked=!r.locked;emit(r)}});
+ s.on('room:kick',id=>{const r=roomOf(s.id);if(!r||r.host!==s.id||id===s.id)return;const p=r.game.players.findIndex(x=>x.id===id);if(p<0)return;const target=io.sockets.sockets.get(id);target?.leave(r.code);r.members.delete(id);r.game.players.splice(p,1);emit(r);target?.emit('room:kicked')});
+ s.on('game:start',(_,ack)=>{const r=roomOf(s.id);if(!r||r.host!==s.id||r.game.players.length<2)return ack?.({ok:false,error:'Need at least 2 players'});if(r.game.players.some(p=>!p.ready))return ack?.({ok:false,error:'Everyone must be ready'});start(r);timer(r);ack?.({ok:true})});
+ s.on('dice:roll',(_,ack)=>{const r=roomOf(s.id);if(!r||r.game.phase!=='playing')return;const i=playerOf(r,s.id);if(i!==r.game.turn||r.game.dice!==null)return ack?.({ok:false,error:'Not your turn'});r.game.dice=roll();r.game.lastAction=`${r.game.players[i].name} rolled ${r.game.dice}`;emit(r);ack?.({ok:true,dice:r.game.dice,legal:legalMoves(r.game,i,r.game.dice)});if(legalMoves(r.game,i,r.game.dice).length===0){setTimeout(()=>{if(r.game.phase==='playing'&&r.game.dice!==null){if(r.game.dice!==6){r.game.turn=(r.game.turn+1)%r.game.players.length}r.game.dice=null;r.game.deadline=Date.now()+20000;emit(r);timer(r)}},700)}});
+ s.on('piece:move',({index},ack)=>{const r=roomOf(s.id);if(!r||r.game.phase!=='playing')return;const i=playerOf(r,s.id);try{const result=movePiece(r.game,i,Number(index));emit(r);ack?.({ok:true,...result});if(r.game.phase==='playing')timer(r)}catch(e){ack?.({ok:false,error:e instanceof Error?e.message:'Illegal move'})}});
+ s.on('rematch',()=>{const r=roomOf(s.id);if(!r||r.game.phase!=='finished'||r.host!==s.id)return;resetForRematch(r.game);emit(r)});
+ s.on('player:mute',muted=>{const r=roomOf(s.id);const p=r?.game.players.find(x=>x.id===s.id);if(p){p.muted=Boolean(muted);emit(r!)}});
+ s.on('matchmaking:join',()=>{queue.add(s.id);const ids=[...queue].filter(id=>io.sockets.sockets.has(id));if(ids.length>=2){const take=ids.slice(0,4);take.forEach(id=>queue.delete(id));const r:Room={code:code(),host:take[0],maxPlayers:take.length,locked:false,game:createGame(),members:new Map()};take.forEach((id,n)=>{const sock=io.sockets.sockets.get(id)!;sock.join(r.code);r.members.set(id,id);r.game.players.push({id,name:id===s.id?'You':`Player ${n+1}`,ready:true,connected:true,color:colors[n],pieces:[0,0,0,0].map(progress=>({progress})),muted:true,lastSeen:Date.now()})});rooms.set(r.code,r);start(r);take.forEach(id=>io.to(id).emit('matchmaking:found',{room:r.code}));timer(r)}});
+ s.on('matchmaking:cancel',()=>queue.delete(s.id));
+ s.on('voice:offer',d=>d?.to&&io.to(d.to).emit('voice:offer',{from:s.id,offer:d.offer}));s.on('voice:answer',d=>d?.to&&io.to(d.to).emit('voice:answer',{from:s.id,answer:d.answer}));s.on('voice:ice-candidate',d=>d?.to&&io.to(d.to).emit('voice:ice-candidate',{from:s.id,candidate:d.candidate}));
+ s.on('disconnect',()=>{queue.delete(s.id);const r=roomOf(s.id);if(!r)return;const p=r.game.players.find(x=>x.id===s.id);if(!p)return;p.connected=false;p.lastSeen=Date.now();emit(r);setTimeout(()=>{if(!p.connected)return;const i=r.game.players.findIndex(x=>x.id===s.id);if(i>=0)r.game.players.splice(i,1);r.members.delete(s.id);if(r.host===s.id)r.host=r.game.players[0]?.id||'';if(!r.game.players.length)rooms.delete(r.code);else emit(r)},30000)});
+});const port=Number(process.env.PORT||3001);http.listen(port,()=>console.log(`Ludo.io server listening on ${port}`));
